# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date requested')),
                ('user', models.CharField(blank=True, default='spongebob', max_length=250)),
                ('status', models.CharField(blank=True, choices=[('SUCCESS', 'no test failures'), ('FAILURE', 'at least one test failed')], default='SUCCESS', max_length=200)),
            ],
            options={
                'ordering': ('posted',),
            },
        ),
    ]
