# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='failed',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='result',
            name='gold_diff',
            field=models.TextField(default=''),
        ),
    ]
