# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_remove_result_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ('-posted',)},
        ),
        migrations.AlterField(
            model_name='result',
            name='failed',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='gold_diff',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.CharField(default='spongebob', max_length=250),
        ),
    ]
