# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_auto_20170809_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.AddField(
            model_name='result',
            name='origin',
            field=models.CharField(default='user:spongebob', max_length=250),
        ),
        migrations.AddField(
            model_name='result',
            name='passed',
            field=models.TextField(blank=True, default=''),
        ),
    ]
