# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_auto_20170809_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='cl',
            field=models.TextField(blank=True, default='NA'),
        ),
        migrations.AddField(
            model_name='result',
            name='platform',
            field=models.TextField(blank=True, default='NA'),
        ),
    ]
