# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_auto_20170809_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='configuration',
            field=models.TextField(blank=True, default='NA'),
        ),
        migrations.AddField(
            model_name='result',
            name='duration_ecl2ix',
            field=models.TextField(blank=True, default='NA'),
        ),
        migrations.AddField(
            model_name='result',
            name='duration_ix',
            field=models.TextField(blank=True, default='NA'),
        ),
        migrations.AddField(
            model_name='result',
            name='instrumentation',
            field=models.TextField(blank=True, default='NA'),
        ),
        migrations.AddField(
            model_name='result',
            name='num_processes_ix',
            field=models.TextField(blank=True, default='NA'),
        ),
        migrations.AddField(
            model_name='result',
            name='num_threads_ix',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='result',
            name='tests',
            field=models.TextField(blank=True, default=''),
        ),
    ]
