# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0008_result_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='num_threads_ix',
            field=models.TextField(blank=True, default='NA'),
        ),
    ]
