# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0010_result_test_suite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='result',
            name='gold_diff',
        ),
        migrations.RemoveField(
            model_name='result',
            name='passed',
        ),
    ]
